version: '3.8'

services:
  proxy:
    container_name: proxy
    hostname: proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PROXY_PATH}/nginx:/etc/nginx
      - ${PROXY_PATH}/certs:/etc/ssl/private
  gateway:
    container_name: gateway
    hostname: gateway
    image: autana-apigateway:latest
    restart: always
    ports:
      - "1978:1978"
      - "10978:10978"
    networks:
      - app_network
    environment:
      - APIGATEWAY_ENDPOINT=${APIGATEWAY_ENDPOINT}
      - APIGATEWAY_PROJECT=${APIGATEWAY_PROJECT}
      - APIGATEWAY_APIKEY=${APIGATEWAY_APIKEY}
      - API_GATEWAY_WEBHOOK_USER=${API_GATEWAY_WEBHOOK_USER}
      - API_GATEWAY_WEBHOOK_PASSWORD=${API_GATEWAY_WEBHOOK_PASSWORD}
networks:
  app_network:
    driver: bridge
