version: '3.8'

services:
  gateway:
    image: autana-apigateway:latest
    restart: always
    ports:
      - "80:80"
      - "10978:10978"
    networks:
      - app_network
    environment:
      - APIGATEWAY_ENDPOINT=${APIGATEWAY_ENDPOINT}
      - APIGATEWAY_PROJECT=${APIGATEWAY_PROJECT}
      - APIGATEWAY_APIKEY=${APIGATEWAY_APIKEY}

networks:
  app_network:
    driver: bridge
